return {
  'folke/which-key.nvim',
  event = 'VimEnter',
  opts = {
    preset = 'helix',
    icons = {
      mappings = vim.g.have_nerd_font,
      keys = vim.g.have_nerd_font and {} or {
        Up = '<Up> ',
        Down = '<Down> ',
        Left = '<Left> ',
        Right = '<Right> ',
        C = '<C-…> ',
        M = '<M-…> ',
        D = '<D-…> ',
        S = '<S-…> ',
        CR = '<CR> ',
        Esc = '<Esc> ',
        ScrollWheelDown = '<ScrollWheelDown> ',
        ScrollWheelUp = '<ScrollWheelUp> ',
        NL = '<NL> ',
        BS = '<BS> ',
        Space = '<Space> ',
        Tab = '<Tab> ',
        F1 = '<F1>',
        F2 = '<F2>',
        F3 = '<F3>',
        F4 = '<F4>',
        F5 = '<F5>',
        F6 = '<F6>',
        F7 = '<F7>',
        F8 = '<F8>',
        F9 = '<F9>',
        F10 = '<F10>',
        F11 = '<F11>',
        F12 = '<F12>',
      },
    },
    spec = {
      { '<leader>a', group = 'Avante', icon = { icon = '󰅭' } },
      { '<leader>c', group = 'Code', mode = { 'n', 'x' }, icon = { icon = '󱐋' } },
      { '<leader>f', group = 'File & Search', icon = { icon = '' } },
      { '<leader>t', group = 'Test', icon = { icon = '󰙨' } },
      { '<leader>g', group = 'Git', icon = { icon = '' } },
      { '<leader>e', group = 'Explorer', icon = { icon = '' } },
      { '<leader>/', group = 'Grep', icon = { icon = '' } },
      { '<leader><leader>', group = 'Find File', icon = { icon = '' } },
      { '<leader>d', group = 'Diagnostics', icon = { icon = '󱖫' } },
      { '<leader>:', group = 'Command History', icon = { icon = '' } },
      { '<leader>h', group = 'Harpoon', icon = { icon = '' } },
      { '<leader>q', group = 'Sessions', icon = { icon = '' } },
      { '<leader>s', group = 'Split', icon = { icon = '' } },
      { '<leader>n', group = 'Nofitications', icon = { icon = '' } },
      { '<leader>l', group = 'Lazy', icon = { icon = '󰒲' } },
      { '<leader>m', group = 'Mason', icon = { icon = '󰏗' } },
      { '<leader>z', group = 'CodeCompanion', icon = { icon = '󰅭' } },
      { '<leader>u', group = 'UI', icon = { icon = '' } },
      { '<leader>.', group = 'Buffer', icon = { icon = '' } },
      {
        '<leader>b',
        icon = { icon = ' ' },
        group = 'Buffer',
        expand = function()
          return require('which-key.extras').expand.buf()
        end,
      },
      {
        '<leader>w',
        group = 'Window',
        proxy = '<c-w>',
        expand = function()
          return require('which-key.extras').expand.win()
        end,
      },
    },
  },
}
